### PR TITLE
fix(async): queue error handling

### PR DESCRIPTION
**Pull request by zaaack**

### CODE REVIEW

**Comment by HairyRabbit** [comment]
would our move this to /queue directory ?

**Comment by zaaack** [comment]
@HairyRabbit Would there be more queues? I put it in /async folder to make the folder structure more compact, if you have any other plan or ideas, just go ahead, I'm fine!

**Comment by HairyRabbit** [comment]
Yeah，because I havn't a good solution about how to organize folder struct. The queue was a normal public data struct, our we implement more struct like stack, or tree.

**Comment by zaaack** [comment]
@HairyRabbit If compare to stack, tree, I think my queue need to rename to something like AsyncQueue...

**Comment by HairyRabbit** [comment]
yes, also AsyncStack or AsyncBST :)

**Pull request merged**
